name: CI Pipeline for LogAnalyzer

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install colorama pytest
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
      
    - name: Execute log analyzer
      run: |
        echo "INFO: Test message" > test.log
        echo "ERROR: Critical failure" >> test.log
        python log_analyzer.py --input test.log --output report.txt
        cat report.txt